Your Kubernetes app is live. Suddenly latency spikes. Users complain.
What will you check first?

Logs? → Too detailed, slow
Traces? → Deep debugging
Metrics? → Fast signal

Metrics = first line of defense

# What is Observability?
Observability is the ability to understand what’s happening inside a system by looking at its outputs.

Logs → What happened
Metrics → How much/how fast
Traces → Where is the delay

############################
What is Prometheus?
“Prometheus is NOT just a tool — it’s a pull-based monitoring system.”

Key Concepts:
- Time-series database
- Pull model (important!)
- Targets + exporters
- Metrics format (key-value pairs)

# Flow
Application → Exposes /metrics → Prometheus scrapes → stores → query (PromQL)

# Push vs Pull Model
| Push (e.g., CloudWatch) | Pull (Prometheus)  |
| ----------------------- | ------------------ |
| App sends data          | Prometheus fetches |
| Hard to control         | Centralized        |
| Less reliable           | More reliable      |


Prometheus is like a health checker — it keeps asking: ‘Are you alive?
##################################

# Kubernetes Challenge
In Kubernetes, pods are dynamic — IP changes, scaling happens.

How will Prometheus know targets?

“This is where Service Discovery comes in.”

Service Discovery is the process that allows a Pod to find the Service in the first place, usually by its human-readable name. 

###################################
# Exporters

“Prometheus cannot understand everything directly.”

So we use:

Node Exporter → system metrics
kube-state-metrics → K8s objects
custom app metrics

# Grafana
Prometheus = storage + brain
Grafana = visualization layer

# Flow
App / Exporters
      ↓
/metrics endpoint
      ↓
Prometheus (scrapes + stores)
      ↓
PromQL queries
      ↓
Grafana dashboards

################################
# Execution

# Application present in local
# Build and push to dockerhub

# Create Deployment and Service

# Install Helm Kube-Prometheus-Stack

# Create ServiceDiscovery
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: observability-servicemonitor
  # namespace: app
  labels:
    release: monitor      # MUST match your Helm release name
    app: observability-app
spec:
  selector:
    matchLabels:          # match service with metadata.labels.app = house-price-serving
      app: observability-app     # MUST match labels in your Service
  namespaceSelector:
    matchNames:
      - default             # your service is in default namespace
  endpoints:
    - port: http            # MUST match service.port.name
      path: /metrics
      interval: 10s
      scrapeTimeout: 5s
